# Generated by Django 5.1.6 on 2025-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="tags",
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("WORKING", "Working"),
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="todo",
            name="tags",
            field=models.TextField(blank=True),
        ),
    ]
