name: Django CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        # services:
        #     postgres:
        #         image: postgres:13
        #         env:
        #             POSTGRES_DB: test_db
        #             POSTGRES_USER: postgres
        #             POSTGRES_PASSWORD: postgres
        #         ports:
        #             - 5432:5432
        #         options: >-
        #             --health-cmd="pg_isready -U postgres"
        #             --health-interval=10s
        #             --health-timeout=5s
        #             --health-retries=5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            # - name: Set up ChromeDriver
            #   uses: actions/setup-chrome-driver@v1

            - name: Install dependencies
              run: | 
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run flake8 (Linting)
              run: flake8 . --statistics

            - name: Run black (Code Formatting Check)
              run: black .

            - name: Run Migrations
              run: |
                python manage.py makemigrations
                python manage.py migrate

            - name: Run Django Server
              run: |
                python manage.py runserver 0.0.0.0:8000 &
                sleep 5     # Give some time to server to start

            - name: Run tests
              run: |
                python manage.py test
